version: "3.3"
services:
    api_gateway:
        build: ./api-gateway
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
            ACCESS_TOKEN_SECRET: eiDEwJCB43aEIXoMaFvp8fKJ2710bFrr
            TODO_SERVICE_BASE_URL: http://todo_service:80/api/todos
            AUTH_SERVICE_BASE_URL: http://auth_service:8010
        networks:
            - distributed-telemetry-tracing-network
    auth_service:
        build: ./auth-service
        ports:
            - "8010:8010"
        environment:
            PORT: 8010
            JWT_SIGNING_KEY: eiDEwJCB43aEIXoMaFvp8fKJ2710bFrr
            USER_SERVICE_BASE_URL: http://user_service:8000
            APPINSIGHTS_INSTRUMENTATIONKEY: Empty
        networks:
            - distributed-telemetry-tracing-network
    todo_service:
        build: ./todo-service
        ports:
            - "80:80"
        environment:
            PORT: 80
        networks:
            - distributed-telemetry-tracing-network
    user_service:
        build: ./user-service
        ports:
            - "8000:8000"
        environment:
            PORT: 8000
            APPINSIGHTS_INSTRUMENTATIONKEY: Empty
        networks:
            - distributed-telemetry-tracing-network

networks:
    distributed-telemetry-tracing-network:
        driver: bridge
