version: "3.3"
services:
    api_gateway:
        build: ./api-gateway
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
            ACCESS_TOKEN_SECRET: MockSigningKey
            TODO_SERVICE_BASE_URL: http://localhost:5000
            AUTH_SERVICE_BASE_URL: http://localhost:8010
    auth_service:
        build: ./auth-service
        ports:
            - "8010:8010"
        environment:
            PORT: 8010
            JWT_SIGNING_KEY: MockSigningKey
            USER_SERVICE_BASE_URL: http://localhost:8000
    todo_service:
        build: ./todo-service
        ports:
            - "5000:5000"
        environment:
            PORT: 5000
    user_service:
        build: ./user-service
        ports:
            - "8000:8000"
        environment:
            PORT: 8000